### ISSUE TITLE
getting error "Command "dev" not found.

### ISSUE THREAD

**Issue by ashitabh** [apache/incubator-kie-kogito-apps#501] opened 2020-10-24 12:48 UTC
When trying to do 
"yarn run dev"
getting following error 
"Command "dev" not found.

**Comment by r00ta** [comment] 2021-02-19 08:16
Hi @ashitabh , are you trying to compile the UI packages?

**Comment by r00ta** [comment] 2021-03-01 09:54
Hi @ashitabh , closing the issue since we can't reproduce it. Feel free to re-open it adding more info

**Closed as completed by r00ta** 2021-03-01 09:54 UTC
